In [19]:
import pandas
import numpy as np

In [20]:
bands = pandas.read_csv("../../cytoBand.txt", sep="\s+",
    names=["chrom", "start", "end", "band", "stain"])
seqlens = pandas.read_csv("../../hg19.genome", sep="\s+",
    names=["chrom", "seqlen"])

In [21]:
seqlens

    chrom     seqlen
0    chr1  249250621
1    chr2  243199373
2    chr3  198022430
3    chr4  191154276
4    chr5  180915260
5    chr6  171115067
6    chr7  159138663
7    chr8  146364022
8    chr9  141213431
9   chr10  135534747
10  chr11  135006516
11  chr12  133851895
12  chr13  115169878
13  chr14  107349540
14  chr15  102531392
15  chr16   90354753
16  chr17   81195210
17  chr18   78077248
18  chr19   59128983
19  chr20   63025520
20  chr21   48129895
21  chr22   51304566

In [38]:
bands[bands["chrom"] == "chr19"]

     chrom     start       end    band   stain
351  chr19         0   6900000   p13.3    gneg
352  chr19   6900000  13900000   p13.2  gpos25
353  chr19  13900000  14000000  p13.13    gneg
354  chr19  14000000  16300000  p13.12  gpos25
355  chr19  16300000  20000000  p13.11    gneg
356  chr19  20000000  24400000     p12    gvar
357  chr19  24400000  26500000     p11    acen
358  chr19  26500000  28600000     q11    acen
359  chr19  28600000  32400000     q12    gvar
360  chr19  32400000  35500000  q13.11    gneg
361  chr19  35500000  38300000  q13.12  gpos25
362  chr19  38300000  38700000  q13.13    gneg
363  chr19  38700000  43400000   q13.2  gpos25
364  chr19  43400000  45200000  q13.31    gneg
365  chr19  45200000  48000000  q13.32  gpos25
366  chr19  48000000  51400000  q13.33    gneg
367  chr19  51400000  53600000  q13.41  gpos25
368  chr19  53600000  56300000  q13.42    gneg
369  chr19  56300000  59128983  q13.43  gpos25

In [37]:
for ii in range(1, 23):
    chrom = f"chr{ii}"
    chrbands = bands[bands["chrom"] == chrom]
    seq_len = np.unique(seqlens[seqlens["chrom"] == chrom]["seqlen"])[0]
    if ii in (13, 14, 15, 21, 22):
        intervals = [[1, seq_len + 1]]
    else:
        centromere = chrbands[chrbands["stain"] == "acen"]
        breakpoint = (np.min(centromere["start"]) + np.max(centromere["end"])) / 2
        intervals = [[1, breakpoint], [breakpoint, seq_len + 1]]
    np.savetxt(f"arms_{chrom}.txt", np.array(intervals), fmt="%d")